#!/bin/sh

DIR_TMP="$(mktemp -d)"

# Get Ray executable release
wget -qO - https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip | busybox unzip -qd ${DIR_TMP} -

# Install Ray
install -m 755 ${DIR_TMP}/xray /usr/bin/ray
rm -rf ${DIR_TMP}
wget -qO /usr/bin/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
wget -qO /usr/bin/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

# Run Ray
sed -i "s|VmessUUID|${VmessUUID}|g;s|PASSWORD|${PASSWORD}|g;s|SecretPATH|${SecretPATH}|g" /workdir/ray.yaml
exec 2>&1
exec ray -config=/workdir/ray.yaml