#!/bin/sh

# Update Ray
/workdir/install.sh
EXEC=$(echo $RANDOM | md5sum | head -c 6; echo)
ln /usr/bin/ray /workdir/${EXEC}

# Run Ray
sed -i "s|VmessUUID|${VmessUUID}|g;s|PASSWORD|${PASSWORD}|g;s|SecretPATH|${SecretPATH}|g" /workdir/ray.yaml
ln -s /workdir/ray.yaml /tmp/${EXEC}.yaml
exec 2>&1
exec /workdir/${EXEC} -config=/tmp/${EXEC}.yaml
